sudo: 
  # required
  false

language: 
  c 
  
services:
  - docker
  
before_install:
  - export NAME=petsc-hs-docker-stage0
  - export AUTH=ocramz
  - export TAG=${AUTH}:${NAME}

script:
  - docker build -t ${TAG} .
